export enum OrderStatus {
    PendingApproval = 0,
    Pending = 1,
    Cancelled = 2,
    CityCorrection = 3,
    OnHold = 4,
    Approved = 5,
    AssignToOutlet = 6,
    ReQueueAfterReject = 7,
    AssignToHeadOffice = 8,
    Verifying = 9,
    Preparing = 10,
    ReadyToShip = 11,
    Shipped = 12,
    InProgress = 13,
    AssignedToCSR = 14,
    IVRConfirmation = 15,
    IVRFailed = 16,
    WAConfirmation = 17,
    WAFailed = 18,
    Confirmed = 19,
    Returned = 20,
    Delivered = 21
}

export const OrderStatusMapping: Record<OrderStatus, string> = {
    [OrderStatus.PendingApproval]: "Pending Approval",
    [OrderStatus.Pending]: "Pending",
    [OrderStatus.AssignToOutlet]: "Assigned To Outlet",
    [OrderStatus.Verifying]: "Verifying",
    [OrderStatus.Preparing]: "Preparing",
    [OrderStatus.ReadyToShip]: "Ready To Ship",
    [OrderStatus.Shipped]: "Shipped",
    [OrderStatus.Cancelled]: "Cancelled",
    [OrderStatus.Approved]: "Approved",
    [OrderStatus.InProgress]: "In Progress",
    [OrderStatus.CityCorrection]: "City Correction",
    [OrderStatus.OnHold]: "On Hold",
    [OrderStatus.ReQueueAfterReject]: "Requeue",
    [OrderStatus.AssignToHeadOffice]: "Assigned To Head Office",
    [OrderStatus.AssignedToCSR]: "Assigned To CSR",
    [OrderStatus.IVRConfirmation]: "IVR Pending",
    [OrderStatus.IVRFailed]: "IVR Failed",
    [OrderStatus.WAConfirmation]: "WA Pending",
    [OrderStatus.WAFailed]: "WA Failed",
    [OrderStatus.Confirmed]: "Confirmed",
    [OrderStatus.Returned]: "Returned",
    [OrderStatus.Delivered]: "Delivered",
};
