import { PaymentMode } from "src/app/core/enums/PaymentMode";
import { PayPeriod } from "src/app/core/enums/PayPeriod";

export interface Employee {
    id: string;
    prefix: string;
    firstName: string;
    lastName: string;
    fullName: string;
    fatherName: string;
    employeeCode: string;
    punchCode: number;
    mobileNo: string;
    phoneNo: string;
    email: string;
    allowManualAttendance: boolean;
    userName: string;
    password: string;
    maritalStatus: string;
    gender: string;
    dateOfBirth: Date;
    placeOfBirth: string;
    familyCode: string;
    religion: string;
    bankAccountNo: string;
    bankAccountTitle: string;
    bankName: string;
    bankBranchCode: string;
    address: string;
    cnicNo: string;
    cnicIssueDate: Date;
    cnicExpireDate: Date;
    departmentId: string;
    designationId: string;
    policyId: string;
    employeeStatus: string;
    joiningDate: Date;
    confirmationDate: Date;
    contractStartDate: Date;
    contractEndDate: Date;
    resignDate: Date;
    imageUrl: string;
    active: boolean;
    reportingTo: string;
    basicSalary: number;
    paymentMode: PaymentMode;
    motherName: string;
    city: string;
    country: string;
    eobiNo: string;
    qualification: string;
    bloodGroup: string;
    languages: string;
    socialSecurityNo: string;
    nicPlace: string;
    domicile: string;
    organizationId: string;
    branchId: string;
    departmentName?: string;
    selected?: boolean;
    payPeriod: PayPeriod;

}
